using Domain.Entities;

namespace Application.ErrorLogs.Dtos;

/// <summary>Every field on <see cref="ErrorLog"/>, returned only when a single error is opened (never in the list) since several fields here (stack trace, request/response bodies) can be large.</summary>
public sealed record ErrorLogDetailDto(
    string Id,
    string ExceptionType,
    string Message,
    string? StackTrace,
    string? InnerException,
    string Source,
    string? ErrorCode,
    string? RequestPath,
    string? HttpMethod,
    string? QueryString,
    string? RequestBody,
    string? IpAddress,
    string? UserAgent,
    string Environment,
    string ApplicationName,
    string? ServiceName,
    string? MachineName,
    string? AssemblyVersion,
    string? TraceId,
    string? CorrelationId,
    string? HangfireJobId,
    string? Provider,
    string? FeedOrApiName,
    string? Country,
    string? SourceUrl,
    int? HttpStatusCode,
    string? ResponseBody,
    TimeSpan? ExecutionDuration,
    string? AdditionalData,
    DateTimeOffset CreatedOn,
    bool IsSent,
    DateTimeOffset? SentOn,
    bool IsResolved,
    DateTimeOffset? ResolvedOn,
    IReadOnlyList<ErrorLogHistoryEntryDto> History)
{
    public static ErrorLogDetailDto FromDomain(ErrorLog log) => new(
        log.Id,
        log.ExceptionType,
        log.Message,
        log.StackTrace,
        log.InnerException,
        log.Source,
        log.ErrorCode,
        log.RequestPath,
        log.HttpMethod,
        log.QueryString,
        log.RequestBody,
        log.IpAddress,
        log.UserAgent,
        log.Environment,
        log.ApplicationName,
        log.ServiceName,
        log.MachineName,
        log.AssemblyVersion,
        log.TraceId,
        log.CorrelationId,
        log.HangfireJobId,
        log.Provider,
        log.FeedOrApiName,
        log.Country,
        log.SourceUrl,
        log.HttpStatusCode,
        log.ResponseBody,
        log.ExecutionDuration,
        log.AdditionalData,
        log.CreatedOn,
        log.IsSent,
        log.SentOn,
        log.IsResolved,
        log.ResolvedOn,
        // Stored oldest-appended-first (Mongo $push appends), reversed here so the UI's history
        // timeline reads newest-first without every consumer needing to know the storage order.
        log.History.Select(ErrorLogHistoryEntryDto.FromDomain).Reverse().ToList());
}
